version: '3.2'

services:
  keycloakDB:
    image: mariadb:latest
    ports:
      - "3406:3306"
    environment:
      MYSQL_ROOT_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    volumes:
      - demo_keycloakdata:/var/lib/mysql

  keycloakservice:
    image: quay.io/keycloak/keycloak:18.0
    # volumes:
    #   - ./imports:/opt/jboss/keycloak/imports
    #   - ./export:/opt/jboss/keycloak-export
    ports:
      - 8080:8080
    command: 
      # - --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
      - start-dev
    environment:
      KC_DB: mariadb
      KC_DB_URL_HOST: keycloakDB
      KC_DB_URL_PORT: "3306"
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      # KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
    depends_on:
      - keycloakDB

volumes:
  demo_keycloakdata:
